name: Blog

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  pull_request:

env:
  # rust 1.68
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  zola:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install zola
        run: |
          # echo "path=$PATH"
          ZOLA_URL=https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
          wget "$ZOLA_URL"
          tar xf zola-*-x86_64-unknown-linux-gnu.tar.gz
          mkdir -p ~/.local/bin
          cp zola ~/.local/bin/
      - run: zola build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
          retention-days: 1

  deploy:
    if: github.event_name != 'pull_request' && github.event.ref == 'refs/heads/main'
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    needs: [zola]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
